---
name: Remove Deployment

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to remove"
        required: true
        default: "development"
        options:
          - production
          - development

jobs:
  deploy-sst:
    name: 🪂 Remove from ${{ inputs.environment }} with SST
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - name: 🏗️ Setup PNPM
        uses: ./.github/actions/setup-app
        with:
          cache-build: true
          cache-opennext: true
      - name: 🪂 Remove from ${{ inputs.environment }} with SST
        run: |
          pnpm dlx sst remove --stage ${{ inputs.environment }} --print-logs
        env:
          # General build settings
          CI: true
          NODE_ENV: production
          TURBO: 1 # Use turbopack for faster builds
          # AWS
          AWS_REGION: "eu-west-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Cloudflare
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_DEFAULT_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_DEFAULT_ACCOUNT_ID }}
          # Tomorrow.io
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          # Sentry
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          # Posthog
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
